var videos = ["https://youtu.be/yE27NwtXjPY?start=1480",
                "https://youtu.be/gq4av949-3Y?start=10148",
                "https://youtu.be/MtS1LGdqxuI?start=10045",
                "https://youtu.be/B5sUXSaTHKc?start=10560",
                "https://youtu.be/iP1gylnxfLU?start=7199",
                "https://youtu.be/2AqLu-u-GcY?start=6245",
                "https://youtu.be/p8p5qZcqIk0?start=3165",
                "https://youtu.be/p8p5qZcqIk0?start=4500",
                "https://youtu.be/WFbmY79Qdfc?start=2155",
                "https://youtu.be/EikRMYRf5-Y?start=1675",
                "https://youtu.be/EikRMYRf5-Y?start=3035",
                "https://youtu.be/EikRMYRf5-Y?start=4331",
                "https://youtu.be/wCj4kCq1Z9Y?start=702",
                "https://youtu.be/wCj4kCq1Z9Y?start=3269",
                "https://youtu.be/wCj4kCq1Z9Y?start=3454",
                "https://youtu.be/wCj4kCq1Z9Y?start=4632",
                "https://youtu.be/9EToAf4nhDw?start=1983",
                "https://youtu.be/9EToAf4nhDw?start=2280",
                "https://youtu.be/9EToAf4nhDw?start=2662",
                "https://youtu.be/9EToAf4nhDw?start=11481",
                "https://youtu.be/0W_by9hT6VQ?start=8121",
                "https://youtu.be/0W_by9hT6VQ?start=8331",
                "https://youtu.be/L8xSI6QoT-A?start=10556",
                "https://youtu.be/qWoloOxtvc0?start=6829",
                "https://youtu.be/qWoloOxtvc0?start=9071",
                "https://youtu.be/zr2n1fLVasU?start=3339",
                "https://youtu.be/zr2n1fLVasU?start=4954",
                "https://youtu.be/KHsA0R_GovU?start=2338",
                "https://youtu.be/0uazTyTrk-8?start=1484",
                "https://youtu.be/0uazTyTrk-8?start=3749",
                "https://youtu.be/0uazTyTrk-8?start=9048",
                "https://youtu.be/uw1crQ1d9AU?start=1359",
                "https://youtu.be/QqU5pqKoH2c?start=1037",
                "https://youtu.be/QqU5pqKoH2c?start=1627",
                "https://youtu.be/1uMH-hFJz0Q?start=5984",
                "https://youtu.be/PfvVssT83MU?start=2377",
                "https://youtu.be/W4e4gTmoGi4?start=4385",
                "https://youtu.be/9QXZ4LfSi84?start=7019",
                "https://youtu.be/Nfcja-6hr24?start=3043",
                "https://youtu.be/Nfcja-6hr24?start=10374",
                "https://youtu.be/Nfcja-6hr24?start=10879",
                "https://youtu.be/A6ma5W_TSDE?start=2293",
                "https://youtu.be/A6ma5W_TSDE?start=15037",
                "https://youtu.be/8xpnCiF4im0?start=1231",
                "https://youtu.be/8xpnCiF4im0?start=2548",
                "https://youtu.be/8xpnCiF4im0?start=3998",
                "https://youtu.be/HMBS__TC5R4?start=2105",
                "https://youtu.be/nRBzpiPccOs?start=11485",
                "https://youtu.be/l_jwMsIv1oc?start=2198",
                "https://youtu.be/l_jwMsIv1oc?start=3373",
                "https://youtu.be/l_jwMsIv1oc?start=3599",
                "https://youtu.be/l_jwMsIv1oc?start=9375",
                "https://youtu.be/YxWU4r-cLIY?start=3494",
                "https://youtu.be/YxWU4r-cLIY?start=5398",
                "https://youtu.be/hejPzXXnPaw",
                "https://youtu.be/um3mkvNmDPY?start=3943",
                "https://youtu.be/um3mkvNmDPY?start=6438",
                "https://youtu.be/DlXEvkhbQqo",
                "https://youtu.be/N7DuwqJtCGI?start=7271",
                "https://youtu.be/9EToAf4nhDw?start=12490",
                "https://youtu.be/uw1crQ1d9AU?start=10454",
                "https://youtu.be/kOaslxt8wyc",
                ]
            
function newVideo() {

    var randomVideo = videos[Math.floor(Math.random() * videos.length)];
    var videoID = randomVideo.split('https://youtu.be/')[1];
    var embedCode = "https://www.youtube.com/embed/" + videoID + "&autoplay=1"
    
    document.getElementById('cr-video').src = embedCode
    document.getElementById('cr-video').contentWindow.focus();

}